services:
  marketplace-api:
    container_name: marketplace-app
    build: ../marketplace-api
    ports:
      - "8081:8081"
    depends_on:
      marketplace-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://marketplace-db:5432/marketplace-db
      SPRING_DATASOURCE_USERNAME: marketplace-db-user
      SPRING_DATASOURCE_PASSWORD: marketplace-db-pass
    healthcheck:
      test: ["CMD", "wget", "-no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - microservices-network

  marketplace-db:
    container_name: marketplace-db
    image: postgres:18.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql"
    environment:
      POSTGRES_DB: marketplace-db
      POSTGRES_USER: marketplace-db-user
      POSTGRES_PASSWORD: marketplace-db-pass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U marketplace-db-user -d marketplace-db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  receiver-api:
    container_name: receiver-app
    build: ../receiver-api
    ports:
      - "8082:8082"
    depends_on:
      receiver-db:
        condition: service_healthy
      marketplace-api:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_HOST: receiver-db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: receiver-db
      SPRING_DATA_MONGODB_USERNAME: receiver-db-user
      SPRING_DATA_MONGODB_PASSWORD: receiver-db-pass
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      MARKETPLACE_API_URL: http://marketplace-app:8081
    healthcheck:
      test: ["CMD", "wget", "-no-verbose", "--tries=1", "--spider", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - microservices-network

  receiver-db:
    container_name: receiver-db
    image: mongo:8.2.4
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
    environment:
      MONGO_INITDB_DATABASE: receiver-db
      MONGO_INITDB_ROOT_USERNAME: receiver-db-user
      MONGO_INITDB_ROOT_PASSWORD: receiver-db-pass
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "mongodb://receiver-db-user:receiver-db-pass@localhost:27017/admin", "--eval", "db.runCommand('ping').ok" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

volumes:
  pg_data:
  mongo_data:

networks:
  microservices-network:
    driver: bridge
