services:
  marketplace-db:
    container_name: marketplace-db

    image: postgres:18.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql"
    environment:
      POSTGRES_DB: marketplace-db
      POSTGRES_USER: marketplace-db-user
      POSTGRES_PASSWORD: marketplace-db-pass
volumes:
  pg_data:
    driver: local
