server:
  port: 8082
spring:
  application:
    name: receiver-api
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    host: ${SPRING_DATA_MONGODB_HOST}
    port: ${SPRING_DATA_MONGODB_PORT}
    database: ${SPRING_DATA_MONGODB_DATABASE}
    username: ${SPRING_DATA_MONGODB_USERNAME}
    password: ${SPRING_DATA_MONGODB_PASSWORD}
    authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
    representation:
      uuid: standard
management:
  endpoint:
    health:
      show-details: always
microservices:
  marketplace-api:
    url: ${MARKETPLACE_API_URL}
